version: 1
labels:
- label: 'proposal'
  title: '(\s|^)(?i)(proposal|Proposal|PROPOSAL)(?-i)(\s|.|$)'
- label: 'final_submission'
  title: '(\s|^)(?i)(final submission|Final Submission|Final submission| FINAL SUBMISSION)(?-i)(\s|.|$)'
- label: 'presentation'
  body: '\bCategory\b(\n*)\b(Presentation|presentation|PRESENTATION)\b'
- label: 'demo'
  body: '\bCategory\b(\n*)\b(Demo|demo|DEMO)\b'
- label: 'course_automation'
  body: '\bCategory\b(\n*)\b(Course automation|course automation|COURSE AUTOMATION)\b'
- label: 'essay'
  body: '\bCategory\b(\n*)\b(Essay|essay|ESSAY)\b'
- label: 'executable_tutorial'
  body: '\bCategory\b(\n*)\b(Executable tutorial|executable tutorial|Executable Tutorial| EXECUTABLE TUTORIAL)\b'
- label: 'feedback'
  body: '\bCategory\b(\n*)\b(Feedback|feedback|FEEDBACK)\b'
