labels:
- label: "proposal"
  title: "(\s|^)(?i)(proposal|Proposal|PROPOSAL)(?-i)(\s|.|$)"
- label: "final_submission"
  title: "(\s|^)(?i)(final submission|Final Submission|Final submission| FINAL SUBMISSION)(?-i)(\s|.|$)"
- label: "presentation"
  body: "\n\bCategory\b\n\b(Presentation|presentation|PRESENTATION)\b\n"
- label: "demo"
  body: "\n\bCategory\b\n\b(Demo|demo|DEMO)\b\n"
- label: "course_automation"
  body: "\n\bCategory\b\n\b(Course automation|course automation|COURSE AUTOMATION)\b\n"
- label: "essay"
  body: "\n\bCategory\b\n\b(Essay|essay|ESSAY)\b\n"
- label: "executable_tutorial"
  body: "\n\bCategory\b\n\b(Executable tutorial|executable tutorial|Executable Tutorial| EXECUTABLE TUTORIAL)\b\n"
- label: "feedback"
  body: "\n\bCategory\b\n\b(Feedback|feedback|FEEDBACK)\b\n"
