name: Essay word counter
on:
  pull_request:
    paths:
      - '**.pdf'
jobs:
  Check-essay:
    runs-on: ubuntu-latest
    steps:
      - name: Install poppler-utils
        run: sudo apt-get install poppler-utils
      - name: Count words in pdf
        run: pdftotext **.pdf | wc -w
