name: Essay word counter
on:
  pull_request:
    paths:
      - '**.pdf'
jobs:
  Check-essay:
    runs-on: ubuntu-latest
    steps:
      - name: Install poppler-utils
        run: sudo apt-get install poppler-utils
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Print working directory and files
        run: |
          ls ${{ github.workspace }}
      - name: Count words in pdf
        run: |
          pdftotext ${{ github.workspace }}/*.pdf | wc -w
