name: Essay word counter

on:
  pull_request:
    paths:
      - '**.pdf'

jobs:
  Check-essay:
    runs-on: ubuntu-latest
    env:
      LOWER_LIMIT: 2400
      UPPER_LIMIT: 2600
    steps:
      - name: Install poppler-utils (Dependency)
        run: sudo apt-get install poppler-utils
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Count words in pdf
        id: word-count
        run: echo ::set-output name=count::$(pdftotext ${{ github.workspace }}/*.pdf - | wc -w)
      - name: Check if count is in allowed interval
        if: ${{steps.word-count.outputs.count < env.LOWER_LIMIT || steps.word-count.outputs.count > env.UPPER_LIMIT}}
        run: exit 1

